    SCREEN 1
    COLOR 9
    PALETTE 2, 0
    LINE (110, 55)-(145, 85), , BF
    LINE (130, 70)-(190, 105), , BF
    LINE (140, 105)-(150, 125), , BF
    LINE (170, 105)-(185, 125), , BF
    LINE (105, 55)-(110, 65), 2, BF
    LINE (110, 55)-(115, 60), 2, BF
    LINE (120, 75)-(130, 85), 2, BF
    LINE (115, 80)-(125, 90), 2, BF
    LINE (140, 55)-(150, 60), 2, BF
    LINE (145, 60)-(150, 65), 2, BF
    LINE (140, 125)-(150, 130), 2, BF
    LINE (170, 125)-(185, 130), 2, BF
    LINE (115, 65)-(120, 70), 2, BF
    LINE (130, 65)-(135, 70), 2, BF
    LINE (190, 75)-(200, 90), 2, BF
    CIRCLE (117, 67), 1, 3
    CIRCLE (132, 67), 1, 3
    PALETTE 1, 10
    LINE (0, 130)-(400, 190), 1, BF
    PRINT ""
    PRINT ""
    PRINT ""
    PRINT ""
    PRINT ""
    PRINT "BAA!!!! BAA!!!!"
    SCALE$ = "EDCDEE"
    PLAY "O3"
    PLAY "L4"
    PLAY "MN"
    PLAY (SCALE$)
    SCALE2$ = "E"
    PLAY "L2"
    PLAY (SCALE2$)
    SCALE3$ = "DD"
    PLAY "L4"
    PLAY (SCALE3$)
    SCALE4$ = "D"
    PLAY "L2"
    PLAY (SCALE4$)
    SCALE5$ = "EG"
    PLAY "L4"
    PLAY (SCALE5$)
    SCALE6$ = "G"
    PLAY "L2"
    PLAY (SCALE6$)
    SCALE7$ = "EDCDEEEEDDED"
    PLAY "L4"
    PLAY (SCALE7$)
    SCALE8$ = "C"
    PLAY "L1"
    PLAY (SCALE8$)
    RUN "A:\STARTUP.BAS"

